package goshopee

type AutoBiddingInfo struct {
	RoasTarget float64 `json:"roas_target"` // [Required] <p>the ROAS target for each campaign with auto bidding</p>
}
type AutoProductAdsInfo struct {
	ProductName string `json:"product_name"` // [Required] <p>the name of product</p>
	Status string `json:"status"` // [Required] <p>learning, ongoing, paused, ended, unavailable<br /></p>
	ItemId int64 `json:"item_id"` // [Required] <p>Unique identifier for the product.</p>
}
type Budget struct {
	RecommendedBudget float64 `json:"recommended_budget"` // [Required] <p>Recommended Suggested Budget</p>
	MinBudget float64 `json:"min_budget"` // [Required] <p>Minimun&nbsp;Suggested Budget</p>
	MaxBudget float64 `json:"max_budget"` // [Required] <p>Maximum&nbsp;Suggested Budget</p>
}
type Campaign struct {
	CampaignId int64 `json:"campaign_id"` // [Required] <p>the unique id per campaign</p>
	AdType string `json:"ad_type"` // [Required] <p>auto, manual<br /></p>
	CampaignPlacement string `json:"campaign_placement"` // [Required] <p>search, discovery, all<br /></p>
	AdName string `json:"ad_name"` // [Required] <p>the name of each ad</p>
	MetricsList []Metrics `json:"metrics_list"` // [Required] <p>the performance metric list</p>
}
type CampaignDuration struct {
	StartTime int64 `json:"start_time"` // [Required] <p>The start date for each campaign. please kindly note that if this campaign is no end date, please pass today's date as the start date&nbsp;</p>
	EndTime int64 `json:"end_time"` // [Required] <p>the end date per campaign. please kindly note that if it's no limit, so you don't need pass anything and if it's unlimited, the end time would return 0</p>
}
type CampaignMetrics struct {
	Hour int64 `json:"hour"` // [Required] <p>This is the parameter to indicate each hour the performance record belongs to.<br /></p>
	Date string `json:"date"` // [Required] <p>This is the parameter of the single date on which requestor wants to check the hourly performance<br /></p>
	Impression int64 `json:"impression"` // [Required] <p>The number of times shoppers see your ad.</p>
	Clicks int64 `json:"clicks"` // [Required] <p>The number of times shoppers click on your ad. (Note: Shopee filters out repeated clicks from the same shopper that occur within a short time frame.)<br /></p>
	Ctr float64 `json:"ctr"` // [Required] <p>The click-through rate (CTR) measures how often shoppers end up clicking on your ad after seeing it. It is the number of clicks on your ad divided by the number of times your ad is seen. CTR = clicks ÷ impressions × 100%.</p>
	Expense float64 `json:"expense"` // [Required] <p>The amount spent on your ad.<br /></p>
	BroadGmv float64 `json:"broad_gmv"` // [Required] <p>The amount of sales revenue generated from shoppers purchasing products within 7 days of them clicking on your ad.<br /></p>
	BroadOrder int64 `json:"broad_order"` // [Required] <p>The number of times shoppers purchased any product from your shop within 7 days of them clicking on your ad.<br /></p>
	BroadOrderAmount int64 `json:"broad_order_amount"` // [Required] <p>The total quantity of products purchased by shoppers within 7 days of them clicking on your ad.<br /></p>
	BroadRoi float64 `json:"broad_roi"` // [Required] <p>Return on ad spend (ROAS) measures how much revenue is generated by your ad relative to the cost of the ad. It is the amount of sales revenue attributed to your ad divided by the amount spent on the ad. ROAS = GMV ÷ expense. (Note: We recommend monitoring ROAS trends on a weekly basis.)<br /></p>
	BroadCir float64 `json:"broad_cir"` // [Required] <p>The advertising cost of sales (ACOS) measures how much your ad costs relative to the revenue the ad generates. It is the amount spent on your ad divided by the amount of sales revenue attributed to the ad. ACOS = expense ÷ GMV × 100%.<br /></p>
	Cr float64 `json:"cr"` // [Required] <p>The conversion rate measures how often shoppers end up purchasing something from your shop after clicking on your ad. It is the number of conversions attributed to your ad divided by the number of clicks on the ad. Conversion rate = conversions ÷ clicks × 100%.<br /></p>
	Cpc float64 `json:"cpc"` // [Required] <p>The cost per conversion is how much each conversion costs, on average. It is the amount spent on your ad divided by the number of conversions attributed to the ad. Cost per conversion = expense ÷ conversions.<br /></p>
	DirectOrder int64 `json:"direct_order"` // [Required] <p>The number of times shoppers purchased the advertised product within 7 days of them clicking on the ad.<br /></p>
	DirectOrderAmount int64 `json:"direct_order_amount"` // [Required] <p>The total quantity of the advertised product purchased by shoppers within 7 days of them clicking on the ad.<br /></p>
	DirectGmv float64 `json:"direct_gmv"` // [Required] <p>The amount of sales revenue generated from shoppers purchasing the advertised product within 7 days of them clicking on the ad.<br /></p>
	DirectRoi float64 `json:"direct_roi"` // [Required] <p>The direct return on ad spend, or direct ROAS, measures how much revenue is generated from sales of the advertised product, relative to the cost of the ad. It is the amount of sales revenue for the advertised product attributed to the ad, divided by the amount spent on the ad. Direct ROAS = direct GMV ÷ expense.<br /></p>
	DirectCir float64 `json:"direct_cir"` // [Required] <p>The direct advertising cost of sales, or direct ACOS, measures how much your ad costs relative to the revenue generated from sales of the advertised product. It is the amount spent on the ad divided by the amount of sales revenue for the advertised product that is attributed to the ad. Direct ACOS = expense ÷ direct GMV × 100%.<br /></p>
	DirectCr float64 `json:"direct_cr"` // [Required] <p>The direct conversion rate measures how often shoppers end up purchasing the advertised product after clicking on the ad. Direct conversion rate is the number of direct conversions divided by the number of clicks. Direct conversion rate = direct conversions ÷ clicks × 100%.<br /></p>
	Cpdc float64 `json:"cpdc"` // [Required] <p>The cost per direct conversion is how much each direct conversion costs, on average. It is the amount spent on your ad divided by the number of direct conversions attributed to the ad. Cost per direct conversion = expense ÷ direct conversions.<br /></p>
}
type CheckCreateGmsProductCampaignEligibilityResponse struct {
	BaseResponse // Common response fields
	Response CheckCreateGmsProductCampaignEligibilityResponseData `json:"response"` // <p><br /></p>
}
type CheckCreateGmsProductCampaignEligibilityResponseData struct {
	IsEligible bool `json:"is_eligible"` // [Required] <p>Indicates if the seller is eligible to create a GMS Campaign</p>
	Reason string `json:"reason"` // [Required] <p>The following are the list of reasons for not being able to create a GMS Campaign:&nbsp;</p><p>active_campaign</p><p>&nbsp;&nbsp;&nbsp;&nbsp;There is already an existing GMS Campaign that is active</p><p>not_whitelisted</p><p>&nbsp;&nbsp;&nbsp;&nbsp;The seller is not whitelisted to sz_shop_gmv_max_feature</p><p>not_have_enough_sku</p><p>&nbsp;&nbsp;&nbsp;&nbsp;The seller does not have enough valid items in the shop</p><p>exclusive_with_other_campaign</p><p>&nbsp;&nbsp;&nbsp;&nbsp;Seller is whitelisted to&nbsp;sz_ads_auto_boost</p>
}
type CommonInfo struct {
	AdType string `json:"ad_type"` // [Required] <p>auto, manual<br /></p>
	AdName string `json:"ad_name"` // [Required] <p>the name of each ad</p>
	CampaignStatus CampaignStatus `json:"campaign_status"` // [Required] <p>ongoing, scheduled, ended, paused, deleted, closed<br /></p>
	BiddingMethod string `json:"bidding_method"` // [Required] <p>auto, manual<br /></p>
	CampaignPlacement string `json:"campaign_placement"` // [Required] <p>search, discovery, all<br /></p>
	CampaignBudget float64 `json:"campaign_budget"` // [Required] <p>The budget per campaign. Please kindly note that if the campaign budget = 0, it means the budget set for this campaign is unlimited</p>
	CampaignDuration *CampaignDuration `json:"campaign_duration"` // [Required] <p>the duration per campaign</p>
	ItemIdList []int64 `json:"item_id_list"` // [Required] <p>List of unique identifiers for all products under this campaign. If the campaign is using auto product selection it can have between zero and many products. If the campaign is using manual product selection, it has exactly one.</p>
}
type CreateGmsProductCampaignRequest struct {
	DailyBudget float64 `json:"daily_budget"` // [Required] <p>Daily budget for Campaign.<br /></p>
	EndDate *string `json:"end_date,omitempty"` // [Optional] <p>End date of Campaign e.g. "30-11-2025". Do not fill if no end date.&nbsp;<br /></p>
	ReferenceId *string `json:"reference_id,omitempty"` // [Optional] <p>Input a string</p>
	RoasTarget *float64 `json:"roas_target,omitempty"` // [Optional] <p>No input will be GMV Max Auto Bidding (Shop).</p><p>Input 0 for GMV Max Auto Bidding (Shop).</p><p>Input greater than 0 for GMV Max Custom ROAS (Shop).</p><p>If value = 10.123456, it will be taken as 10.1</p><p>If value = 10.199999, it will be taken as 10.1</p>
	StartDate string `json:"start_date"` // [Required] <p>Start date of Campaign e.g. "30-11-2025". Cannot be earlier than today.<br /></p>
}
type CreateGmsProductCampaignResponse struct {
	BaseResponse // Common response fields
	Response CreateGmsProductCampaignResponseData `json:"response"` // 
}
type CreateGmsProductCampaignResponseData struct {
	CampaignId int64 `json:"campaign_id"` // [Required] <p>GMS Campaign ID.<br /></p>
}
type CreateManualProductAdsRequest struct {
	BiddingMethod string `json:"bidding_method"` // [Required] <p>auto, manual<br /></p>
	Budget float64 `json:"budget"` // [Required] <p>The budget set for the Auto Product Ads<br /></p>
	DiscoveryAdsLocations []DiscoveryAdsLocations `json:"discovery_ads_locations,omitempty"` // [Optional] <p>the location settings for manual bidding method</p>
	EndDate *string `json:"end_date,omitempty"` // [Optional] <p>the end date of each campaign. please kindly note that if you want to set an unlimited campaign, you can keep empty for the end date field</p>
	EnhancedCpc *bool `json:"enhanced_cpc,omitempty"` // [Optional] <p>Enhanced CPC functionality toggle</p>
	ItemId int64 `json:"item_id"` // [Required] <p>Product ID</p>
	ReferenceId string `json:"reference_id"` // [Required] <p>A random string used to prevent duplicate ads. If an ads is created successfully, subsequent request using the same reference id will fail<br /></p>
	RoasTarget *float64 `json:"roas_target,omitempty"` // [Optional] <p>the ROAS target for each campaign with auto bidding. If 0, GMV Max / ROI feature is not enabled</p>
	SelectedKeywords []SelectedKeywords `json:"selected_keywords,omitempty"` // [Optional] <p>selected keywords, required for manual bidding mode</p>
	SmartCreativeSetting *string `json:"smart_creative_setting,omitempty"` // [Optional] <p>Whether to use default or set on/off Smart Creative for this ad. Supported Values: "", "default", "on", "off". Empty string treated as default.</p>
	StartDate string `json:"start_date"` // [Required] <p>the start date per campaign. please kindly note that if you want to set unlimited date, you can just pass today's date as the start date</p>
}
type CreateManualProductAdsResponse struct {
	BaseResponse // Common response fields
	Response CreateManualProductAdsResponseData `json:"response"` // <p>response body<br /></p>
}
type CreateManualProductAdsResponseData struct {
	CampaignId int64 `json:"campaign_id"` // [Required] <p>The unique identifier for a campaign<br /></p>
}
type DiscoveryAdsLocations struct {
	Location string `json:"location"` // [Required] <p>daily_discover, you_may_also_like<br /></p>
	BidPrice float64 `json:"bid_price"` // [Required] <p>bid price of the location</p>
}
type EditGmsItemProductCampaignRequest struct {
	CampaignId *int64 `json:"campaign_id,omitempty"` // [Optional] <p>The GMS Campaign ID. Provide if available.<br /></p>
	EditAction string `json:"edit_action"` // [Required] <p>The following is the list of possible actions:</p><p>&nbsp;&nbsp;&nbsp;&nbsp;add</p><p>&nbsp;&nbsp;&nbsp;&nbsp;remove</p>
	ItemIdList []int64 `json:"item_id_list"` // [Required] <p>Item IDs to add / remove. Minimum 1 Item ID. Maximum 30 Item IDs.<br /></p>
}
type EditGmsItemProductCampaignResponse struct {
	BaseResponse // Common response fields
	Response EditGmsItemProductCampaignResponseData `json:"response"` // 
}
type EditGmsItemProductCampaignResponseData struct {
	CampaignId int64 `json:"campaign_id"` // [Required] <p>GMS Campaign ID<br /></p>
}
type EditGmsProductCampaignRequest struct {
	CampaignId *int64 `json:"campaign_id,omitempty"` // [Optional] <p>The GMS Campaign ID. Provide if available.<br /></p>
	DailyBudget *float64 `json:"daily_budget,omitempty"` // [Optional] <p>Daily budget for Campaign.<br /></p>
	EditAction string `json:"edit_action"` // [Required] <p>The following is the list of possible actions and their required fields:</p><p>1.change_budgetdaily_budget</p><p>2.change_durationstart_date</p><p>3.end_date</p><p>4.pause</p><p>5.resume</p><p>6.start</p><p>7.change_roas_targetroas_target: when edit_action = change_roas_target, you must provide:</p><p>roas_target (float) Value rules follow the same logic as in the create endpoint</p>
	EndDate *string `json:"end_date,omitempty"` // [Optional] <p>End date of Campaign e.g. "11-11-2025". Do not fill if no end date.&nbsp;<br /></p>
	ReferenceId *string `json:"reference_id,omitempty"` // [Optional] <p>Generated by developers, used to prevent duplicate requests</p><p>Submitting the same reference_id more than once will fail; a new reference_id must be generated to retry.</p><p></p><p>Example: 086a16bf-49e9-4103-b7fe-c0125beb9278</p>
	RoasTarget *float64 `json:"roas_target,omitempty"` // [Optional] <p>No input will be GMV Max Auto Bidding (Shop).</p><p>Input 0 for GMV Max Auto Bidding (Shop).</p><p>Input greater than 0 for GMV Max Custom ROAS (Shop).</p><p>If value = 10.123456, it will be taken as 10.1</p><p>If value = 10.199999, it will be taken as 10.1</p>
	StartDate *string `json:"start_date,omitempty"` // [Optional] <p>Start date of Campaign e.g. "11-11-2025". Cannot be earlier than today.<br /></p>
}
type EditGmsProductCampaignResponse struct {
	BaseResponse // Common response fields
	Response EditGmsProductCampaignResponseData `json:"response"` // 
}
type EditGmsProductCampaignResponseData struct {
	CampaignId int64 `json:"campaign_id"` // [Required] <p>GMS Campaign ID<br /></p>
}
type EditManualProductAdKeywordsRequest struct {
	CampaignId int64 `json:"campaign_id"` // [Required] <p>The unique identifier for a campaign<br /></p>
	ReferenceId string `json:"reference_id"` // [Required] <p>A random string used to prevent duplicate ads. If an ads is created successfully, subsequent request using the same reference id will fail<br /></p>
	SelectedKeywords []RequestSelectedKeywords `json:"selected_keywords"` // [Required] <p>selected keywords, required for manual bidding mode.</p>
}
type EditManualProductAdKeywordsResponse struct {
	BaseResponse // Common response fields
	Response EditManualProductAdKeywordsResponseData `json:"response"` // <p>response body<br /></p>
}
type EditManualProductAdKeywordsResponseData struct {
	CampaignId int64 `json:"campaign_id"` // [Required] <p>The unique identifier for a campaign<br /></p>
	FailedEdits []FailedEdits `json:"failed_edits"` // [Required] <p>failed edits are mentioned here</p>
}
type EditManualProductAdsRequest struct {
	Budget *float64 `json:"budget,omitempty"` // [Optional] <p>The budget set for the Auto Product Ads<br /></p>
	CampaignId int64 `json:"campaign_id"` // [Required] <p>The unique identifier for a campaign<br /></p>
	DiscoveryAdsLocations []RequestDiscoveryAdsLocations `json:"discovery_ads_locations,omitempty"` // [Optional] <p>the location settings for manual bidding method</p>
	EditAction string `json:"edit_action"` // [Required] <p>Actions supported:&nbsp;<br />"start", "pause", "resume", "stop", "delete", "change_budget", "change_duration", "change_smart_creative", "change_location", "change_enhanced_cpc", "change_roas_target"</p>
	EndDate *string `json:"end_date,omitempty"` // [Optional] <p>the end date of each campaign. please kindly note that if you want to set an unlimited campaign, you can keep empty for the end date field</p>
	EnhancedCpc *bool `json:"enhanced_cpc,omitempty"` // [Optional] <p>Enhanced CPC functionality toggle</p>
	ReferenceId string `json:"reference_id"` // [Required] <p>A random string used to prevent duplicate ads. If an ads is created successfully, subsequent request using the same reference id will fail<br /></p>
	RoasTarget *float64 `json:"roas_target,omitempty"` // [Optional] <p>the ROAS target for each campaign with auto bidding</p>
	SmartCreativeSetting *string `json:"smart_creative_setting,omitempty"` // [Optional] <p>Whether to use default or set on/off Smart Creative for this ad. Supported Values: "", "default", "on", "off". Empty string treated as default.<br /></p>
	StartDate *string `json:"start_date,omitempty"` // [Optional] <p>the start date per campaign. please kindly note that if you want to set unlimited date, you can just pass today's date as the start date</p>
}
type EditManualProductAdsResponse struct {
	BaseResponse // Common response fields
	Response EditManualProductAdsResponseData `json:"response"` // <p>response body<br /></p>
}
type EditManualProductAdsResponseData struct {
	CampaignId int64 `json:"campaign_id"` // [Required] <p>The unique identifier for a campaign<br /></p>
}
type FailedEdits struct {
	Keyword string `json:"keyword"` // [Required] <p>keyword that failed to update</p>
	Error string `json:"error"` // [Required] <p>Error code</p>
	Message string `json:"message"` // [Required] <p>error description</p>
}
type GetAdsFcilShopRateResponse struct {
	BaseResponse // Common response fields
	Rate float64 `json:"rate,omitempty"` // <p>The rate of the shop who choose to participate in this program</p>
	UpdateAt int64 `json:"update_at,omitempty"` // <p>The update time in timestamp format</p>
}
type GetAllCpcAdsDailyPerformanceRequest struct {
	EndDate string `json:"end_date" url:"end_date"` // [Required] <p>This is the parameter to indicate the end date of the time length of performance<br /></p>
	StartDate string `json:"start_date" url:"start_date"` // [Required] <p>This is the parameter to indicate the start date of the time length of performance.<br /></p>
}
type GetAllCpcAdsDailyPerformanceResponse struct {
	BaseResponse // Common response fields
	Response GetAllCpcAdsDailyPerformanceResponseData `json:"response"` // <p>response body<br /></p>
}
type GetAllCpcAdsDailyPerformanceResponseData struct {
	Date string `json:"date"` // [Required] <p>This is the parameter to indicate which date the performance record belongs to.<br /></p>
	Impression int64 `json:"impression"` // [Required] <p>Number of times buyers see ads<br /></p>
	Clicks int64 `json:"clicks"` // [Required] <p>Total number of clicks on the Ad<br /></p>
	Ctr float64 `json:"ctr"` // [Required] <p>Ctr, click-through rate measures how often shoppers who see an ad end up clicking it. CTR = Clicks / Impressions<br /></p>
	DirectOrder int64 `json:"direct_order"` // [Required] <p>Buyer place an order within 7 days after clicking on the ads (item gets purchased from the clicked ads)<br /></p><p><u>Please kindly note that the&nbsp;<b>direct_order</b>&nbsp;in the API reflected to Seller Center - Shopee Ads Module FE is&nbsp;<b>Direct Conversions.</b></u><br /></p>
	BroadOrder int64 `json:"broad_order"` // [Required] <p>Buyer place an order within 7 days after clicking on the ads; (the item gets purchased as long as there are other items from the same shops got click.)<br /></p><p><u>Please kindly note that the <b>broad_order</b>&nbsp;in the API reflected to Seller Center - Shopee Ads Module FE</u><u>&nbsp;is <b>Conversions</b>.</u></p>
	DirectConversions float64 `json:"direct_conversions"` // [Required] <p>Ad orders / total number of clicks on the Ad. (item gets purchased from the clicked ads.)<br /></p><p><u>Please kindly note that the&nbsp;<b>direct_conversions</b> in the API reflected to Seller Center - Shopee Ads Module FE is&nbsp;<b>Direct Conversions Rate</b>.</u><br /></p>
	BroadConversions float64 `json:"broad_conversions"` // [Required] <p>Ad orders / total number of clicks on the Ad. (the item gets purchased as long as there are other items from the same shops got click.)<br /></p><p><u>Please kindly note that the <b>broad_conversions</b>&nbsp;in the API reflected to Seller Center - Shopee Ads Module FE is <b>Conversions Rate</b>.</u><br /></p>
	DirectItemSold int64 `json:"direct_item_sold"` // [Required] <p>item sold within 7 days after clicking on the ads. (item gets purchased from the clicked ads.)<br /></p>
	BroadItemSold int64 `json:"broad_item_sold"` // [Required] <p>item sold within 7 days after clicking on the ads.(the item gets purchased as long as there are other items from the same shops got click.)<br /></p><p><u>Please kindly note that the <b>broad_conversions</b> in the API reflected to Advertiser Platform is <b>Conversion Rate</b>.</u><br /></p>
	DirectGmv float64 `json:"direct_gmv"` // [Required] <p>Total sales generated from Ad over a certain time frame Typically 7 days. (item gets purchased from the clicked ads.)<br /></p>
	BroadGmv float64 `json:"broad_gmv"` // [Required] <p>Total sales generated from Ad over a certain time frame (the item gets purchased as long as there are other items from the same shops got click.)<br /></p>
	Expense float64 `json:"expense"` // [Required] <p>Ad Expenditure<br /></p>
	CostPerConversion float64 `json:"cost_per_conversion"` // [Required] <p>(Cost Per Conversion) Ad's average cost per sales conversion<br /></p>
	DirectRoas float64 `json:"direct_roas"` // [Required] <p>Ad GMV/Ad Expenditure. (item gets purchased from the clicked ads.)<br /></p>
	BroadRoas float64 `json:"broad_roas"` // [Required] <p>Ad GMV/Ad Expenditure. (the item gets purchased as long as there are other items from the same shops got click.)<br /></p>
}
type GetAllCpcAdsHourlyPerformanceRequest struct {
	PerformanceDate string `json:"performance_date" url:"performance_date"` // [Required] <p>This is the parameter of the single date on which requester wants to check the hourly performance. Date in DD-MM-YYYY format.<br /></p>
}
type GetAllCpcAdsHourlyPerformanceResponse struct {
	BaseResponse // Common response fields
	Response GetAllCpcAdsHourlyPerformanceResponseData `json:"response"` // <p>response body<br /></p>
}
type GetAllCpcAdsHourlyPerformanceResponseData struct {
	Hour int64 `json:"hour"` // [Required] <p>This is the parameter to indicate each hour the performance record belongs to.<br /></p>
	Date string `json:"date"` // [Required] <p>This is the parameter to indicate which date the performance record belongs to.<br /></p>
	Impression int64 `json:"impression"` // [Required] <p>Number of times buyers see ads<br /></p>
	Clicks int64 `json:"clicks"` // [Required] <p>Total number of clicks on the Ad<br /></p>
	Ctr float64 `json:"ctr"` // [Required] <p>Ctr, click-through rate measures how often shoppers who see an ad end up clicking it. CTR = Clicks / Impressions<br /></p>
	DirectOrder int64 `json:"direct_order"` // [Required] <p>Buyer place an order within 7 days after clicking on the ads (item gets purchased from the clicked ads).<br /></p><p><u>Please kindly note that the <b>direct_order</b>&nbsp;in the API reflected to Seller Center Shopee Ads Module FE is <b>Direct Conversions.</b></u></p>
	BroadOrder int64 `json:"broad_order"` // [Required] <p>Buyer place an order within 7 days after clicking on the ads; (the item gets purchased as long as there are other items from the same shops got click.)<br /></p><p><u>Please kindly note that the<b> broad_order </b>in the API<b>&nbsp;</b>reflected to Seller Center Shopee Ads Module FE is <b>Conversions.</b></u></p>
	DirectConversions float64 `json:"direct_conversions"` // [Required] <p>Ad orders / total number of clicks on the Ad. (item gets purchased from the clicked ads.)<br /></p><p><u>Please kindly note that the <b>direct_conversions</b> in the API reflected to Seller Center Shopee Ads Module FE is the&nbsp;<b>Direct Conversion Rate</b></u></p>
	BroadConversions float64 `json:"broad_conversions"` // [Required] <p>Ad orders / total number of clicks on the Ad. (the item gets purchased as long as there are other items from the same shops got click.)<br /></p><p><u>Please kindly note that the <b>broad conversions</b> in the API reflected to Seller Center Shopee Ads Module FE is <b>Conversion Rate</b></u></p>
	DirectItemSold int64 `json:"direct_item_sold"` // [Required] <p>item sold within 7 days after clicking on the ads. (item gets purchased from the clicked ads.)<br /></p>
	BroadItemSold int64 `json:"broad_item_sold"` // [Required] <p>item sold within 7 days after clicking on the ads.(the item gets purchased as long as there are other items from the same shops got click.)<br /></p>
	DirectGmv float64 `json:"direct_gmv"` // [Required] <p>Total sales generated from Ad over a certain time frame Typically 7 days. (item gets purchased from the clicked ads.)<br /></p>
	BroadGmv float64 `json:"broad_gmv"` // [Required] <p>Total sales generated from Ad over a certain time frame (the item gets purchased as long as there are other items from the same shops got click.)<br /></p>
	Expense float64 `json:"expense"` // [Required] <p>Ad Expenditure<br /></p>
	CostPerConversion float64 `json:"cost_per_conversion"` // [Required] <p>(Cost Per Conversion) Ad's average cost per sales conversion<br /></p>
	DirectRoas float64 `json:"direct_roas"` // [Required] <p>Ad GMV/Ad Expenditure. (item gets purchased from the clicked ads.)<br /></p>
	BroadRoas float64 `json:"broad_roas"` // [Required] <p>Ad GMV/Ad Expenditure. (the item gets purchased as long as there are other items from the same shops got click.)<br /></p>
}
type GetCreateProductAdBudgetSuggestionRequest struct {
	BiddingMethod string `json:"bidding_method" url:"bidding_method"` // [Required] <p>Bidding Method of product ad: auto, manual</p>
	CampaignPlacement string `json:"campaign_placement" url:"campaign_placement"` // [Required] <p>search, discovery, all<br /></p>
	DiscoveryAdsLocationNames *string `json:"discovery_ads_location_names,omitempty" url:"discovery_ads_location_names,omitempty"` // [Optional] <p>List of comma separated location values from: daily_discover, you_may_also_like.<br /></p><p>Mandatory for product_selection=manual, product_placement={all|discovery}, bidding_method=manual</p>
	EnhancedCpc *string `json:"enhanced_cpc,omitempty" url:"enhanced_cpc,omitempty"` // [Optional] <p>Enhanced CPC functionality toggle. Values supported "true"/"false". Mandatory for product_selection=manual, bidding_method=manual</p>
	ItemId *int64 `json:"item_id,omitempty" url:"item_id,omitempty"` // [Optional] <p>Product ID. Mandatory for product_selection=manual</p>
	ProductSelection string `json:"product_selection" url:"product_selection"` // [Required] <p>auto,manual - for Auto product ads or Manual Product Ads</p>
	ReferenceId string `json:"reference_id" url:"reference_id"` // [Required] <p>A random string used to prevent duplicate ads. If an ads is created successfully, subsequent request using the same reference id will fail<br /></p>
	RoasTarget *float64 `json:"roas_target,omitempty" url:"roas_target,omitempty"` // [Optional] <p>the ROAS target for each campaign with auto bidding. If 0, GMV Max / ROI feature is not enabled</p>
}
type GetCreateProductAdBudgetSuggestionResponse struct {
	BaseResponse // Common response fields
	Response GetCreateProductAdBudgetSuggestionResponseData `json:"response"` // <p>response body<br /></p>
}
type GetCreateProductAdBudgetSuggestionResponseData struct {
	Budget *Budget `json:"budget"` // [Required] <p>Budget data</p>
}
type GetGmsCampaignPerformanceRequest struct {
	CampaignId *int64 `json:"campaign_id,omitempty"` // [Optional] <p>The GMS Campaign ID. Provide if available.<br /></p>
	EndDate string `json:"end_date"` // [Required] <p>End date of Campaign e.g. "11-11-2025". Maximum duration of 3 months between start_date &amp; end_date.<br /></p>
	StartDate string `json:"start_date"` // [Required] <p>Start date of Campaign e.g. "11-11-2025". Maximum duration of 3 months between start_date &amp; end_date. Earliest start_date is 6 months before today.<br /></p>
}
type GetGmsCampaignPerformanceResponse struct {
	BaseResponse // Common response fields
	Response GetGmsCampaignPerformanceResponseData `json:"response"` // 
}
type GetGmsCampaignPerformanceResponseData struct {
	CampaignId int64 `json:"campaign_id"` // [Required] <p>GMS Campaign ID<br /></p>
	Report *Report `json:"report"` // [Required] 
}
type GetGmsItemPerformanceRequest struct {
	CampaignId *int64 `json:"campaign_id,omitempty"` // [Optional] <p>The GMS Campaign ID. Provide if available.<br /></p>
	EndDate string `json:"end_date"` // [Required] <p>End date of Campaign e.g. "11-11-2025". Maximum duration of 3 months between start_date &amp; end_date.<br /></p>
	Limit *int64 `json:"limit,omitempty"` // [Optional] <p>Specifies the maximum number of records to show. Default is 50. Maximum is 100.<br /></p>
	Offset *int64 `json:"offset,omitempty"` // [Optional] <p>Specifies the starting point, or the number of records to skip. Default is 0.</p>
	StartDate string `json:"start_date"` // [Required] <p>Start date of Campaign e.g. "11-11-2025". Maximum duration of 3 months between start_date &amp; end_date. Earliest start_date is 6 months before today.<br /></p>
}
type GetGmsItemPerformanceResponse struct {
	BaseResponse // Common response fields
	Response GetGmsItemPerformanceResponseData `json:"response"` // 
}
type GetGmsItemPerformanceResponseData struct {
	CampaignId int64 `json:"campaign_id"` // [Required] <p>GMS Campaign ID<br /></p>
	ResultList []Result `json:"result_list"` // [Required] 
	Total int64 `json:"total"` // [Required] <p>Total number of Item ID reports.<br /></p>
	HasNextPage bool `json:"has_next_page"` // [Required] <p>Indicate that there are more item ID reports.<br /></p>
}
type GetProductCampaignDailyPerformanceRequest struct {
	CampaignIdList string `json:"campaign_id_list" url:"campaign_id_list"` // [Required] <p>The campaign ids (comma separated) you want to fetch the performance. (max 100)<br /></p>
	EndDate string `json:"end_date" url:"end_date"` // [Required] <p>This is the parameter to indicate the end date of the time length of performance<br /></p>
	StartDate string `json:"start_date" url:"start_date"` // [Required] <p>This is the parameter to indicate the start date of the time length of performance.<br /></p>
}
type GetProductCampaignDailyPerformanceResponse struct {
	BaseResponse // Common response fields
	Response GetProductCampaignDailyPerformanceResponseData `json:"response"` // <p>response body<br /></p>
}
type GetProductCampaignDailyPerformanceResponseData struct {
	ShopId int64 `json:"shop_id"` // [Required] <p>the unique id per shop&nbsp;</p>
	Region string `json:"region"` // [Required] <p>the region where each shop is under</p>
	CampaignList []Campaign `json:"campaign_list"` // [Required] <p>the list of campaign</p>
}
type GetProductCampaignHourlyPerformanceRequest struct {
	CampaignIdList string `json:"campaign_id_list" url:"campaign_id_list"` // [Required] <p>The campaign ids (comma separated) you want to fetch the performance. (max 100)<br /></p>
	PerformanceDate string `json:"performance_date" url:"performance_date"` // [Required] <p>This is the parameter to indicate the start date of the time length of performance.<br /></p>
}
type GetProductCampaignHourlyPerformanceResponse struct {
	BaseResponse // Common response fields
	Response GetProductCampaignHourlyPerformanceResponseData `json:"response"` // <p>response body<br /></p>
}
type GetProductCampaignHourlyPerformanceResponseData struct {
	ShopId int64 `json:"shop_id"` // [Required] <p>Shopee's unique identifier for a shop<br /></p>
	Region string `json:"region"` // [Required] <p>The region where this Shop is under<br /></p>
	CampaignList []ResponseDataCampaign `json:"campaign_list"` // [Required] <p>the list of campaign</p>
}
type GetProductLevelCampaignIdListRequest struct {
	AdType *string `json:"ad_type,omitempty" url:"ad_type,omitempty"` // [Optional] <p>Any of ["","all","auto","manual"]</p>
	Limit *int64 `json:"limit,omitempty" url:"limit,omitempty"` // [Optional] <p>limit</p>
	Offset *int64 `json:"offset,omitempty" url:"offset,omitempty"` // [Optional] <p>offset</p>
}
type GetProductLevelCampaignIdListResponse struct {
	BaseResponse // Common response fields
	Response GetProductLevelCampaignIdListResponseData `json:"response"` // <p>response body<br /></p>
}
type GetProductLevelCampaignIdListResponseData struct {
	ShopId int64 `json:"shop_id"` // [Required] <p>Shopee's unique identifier for a shop.<br /></p>
	Region string `json:"region"` // [Required] <p>Region the shop belongs to</p>
	HasNextPage bool `json:"has_next_page"` // [Required] <p>there are more campaigns on next page</p>
	CampaignList []GetProductLevelCampaignIdListResponseDataCampaign `json:"campaign_list"` // [Required] <p>the list of campaigns</p>
}
type GetProductLevelCampaignIdListResponseDataCampaign struct {
	AdType string `json:"ad_type"` // [Required] <p>auto/manual</p>
	CampaignId int64 `json:"campaign_id"` // [Required] <p>the unique id per campaign</p>
}
type GetProductLevelCampaignSettingInfoRequest struct {
	CampaignIdList string `json:"campaign_id_list" url:"campaign_id_list"` // [Required] <p>list of campaign ids comma separated (max 100 campaign ids)</p>
	InfoTypeList string `json:"info_type_list" url:"info_type_list"` // [Required] <p>Info type values: 1.Common Info 2.Manual Bidding Info 3.Auto Bidding Info 4.Auto Product Ads Info</p>
}
type GetProductLevelCampaignSettingInfoResponse struct {
	BaseResponse // Common response fields
	Response GetProductLevelCampaignSettingInfoResponseData `json:"response"` // <p>response body<br /></p>
}
type GetProductLevelCampaignSettingInfoResponseData struct {
	ShopId int64 `json:"shop_id"` // [Required] <p>Shopee's unique identifier for a shop.<br /></p>
	Region string `json:"region"` // [Required] <p>Region the shop belongs to</p>
	CampaignList []GetProductLevelCampaignSettingInfoResponseDataCampaign `json:"campaign_list"` // [Required] <p>-</p>
}
type GetProductLevelCampaignSettingInfoResponseDataCampaign struct {
	CampaignId int64 `json:"campaign_id"` // [Required] <p>The unique ID per campaign</p>
	CommonInfo *CommonInfo `json:"common_info"` // [Required] <p>common_info body</p>
	ManualBiddingInfo *ManualBiddingInfo `json:"manual_bidding_info"` // [Required] <p>manual bidding info</p>
	AutoBiddingInfo *AutoBiddingInfo `json:"auto_bidding_info"` // [Required] <p>bidding info</p>
	AutoProductAdsInfo []AutoProductAdsInfo `json:"auto_product_ads_info"` // [Required] <p>selected products info</p>
}
type GetProductRecommendedRoiTargetRequest struct {
	ItemId int64 `json:"item_id" url:"item_id"` // [Required] <p>Unique identifier for a product.</p>
	ReferenceId string `json:"reference_id" url:"reference_id"` // [Required] <p>A random string used to prevent duplicate ads. If an ads is created successfully, subsequent requests using the same reference id will fail - in this case, a new one must be generated.<br /><br />Use the same string for calling suggestion/recommendation API before the actual request to create an ads.<br /><br /><br /></p>
}
type GetProductRecommendedRoiTargetResponse struct {
	BaseResponse // Common response fields
	Response GetProductRecommendedRoiTargetResponseData `json:"response"` // <p>Response body.</p>
}
type GetProductRecommendedRoiTargetResponseData struct {
	LowerBound *LowerBound `json:"lower_bound"` // [Required] <pre><span style="font-family:Roboto, &quot;Helvetica Neue&quot;, Helvetica, &quot;Droid Sans&quot;, Arial, sans-serif;">Lower bound recommendation.  e.g., value=3.5 and percentile=80 mean that setting an ROI target of 3.5 </span></pre><pre><span style="font-family:Roboto, &quot;Helvetica Neue&quot;, Helvetica, &quot;Droid Sans&quot;, Arial, sans-serif;">makes the ads more competitive than 80% of similar ads.</span></pre>
	Exact *LowerBound `json:"exact"` // [Required] <p><span style="font-size:14px;">Mid-level recommendation&nbsp;</span></p><p><span style="font-size:14px;">e.g., value=5.9 and percentile=50 mean that setting an ROI target of 5.9 makes the ads more competitive than 50% of similar ads.</span></p>
	UpperBound *LowerBound `json:"upper_bound"` // [Required] <p>Higher bound recommendation.</p><p>e.g., value=10.8 and percentile=20 mean that setting an ROI target of 10.8 makes the ads more competitive than 20% of similar ads.</p>
}
type GetRecommendedItemListResponse struct {
	BaseResponse // Common response fields
	Response GetRecommendedItemListResponseData `json:"response"` // <p>response body<br /></p>
}
type GetRecommendedItemListResponseData struct {
	ItemId int64 `json:"item_id"` // [Required] <p>Recommended SKU's item id<br /></p>
	ItemStatusList []string `json:"item_status_list"` // [Required] <p>This is param to indicate the status of items, so sellers can know whether an item is eligible for ads or not.<br /></p>
	SkuTagList []string `json:"sku_tag_list"` // [Required] <p>The&nbsp;corresponding tag (or tags) that belong to item_id, sequences follow as best selling&gt;best ROI&gt;top search<br /></p>
	OngoingAdTypeList []string `json:"ongoing_ad_type_list"` // [Required] <p>Current status of the ad on this item. For example- no ongoing promotion, search ads, discovery ads, boost ads<br /></p>
}
type GetRecommendedKeywordListRequest struct {
	InputKeyword *string `json:"input_keyword,omitempty" url:"input_keyword,omitempty"` // [Optional] <p>The keyword seller typed in the manually add keyword window.<br /></p>
	ItemId int64 `json:"item_id" url:"item_id"` // [Required] <p>Shopee's unique identifier for an item.<br /></p>
}
type GetRecommendedKeywordListResponse struct {
	BaseResponse // Common response fields
	Response GetRecommendedKeywordListResponseData `json:"response"` // <p>response body<br /></p>
}
type GetRecommendedKeywordListResponseData struct {
	ItemId int64 `json:"item_id"` // [Required] <p>Shopee's unique identifier for an item.<br /></p>
	InputKeyword string `json:"input_keyword"` // [Required] <p>The keyword seller typed in the manually add keyword window.<br /></p>
	SuggestedKeywords []SuggestedKeywords `json:"suggested_keywords"` // [Required] <p>Suggested keywords recommended from product.<br /></p>
}
type GetShopToggleInfoResponse struct {
	BaseResponse // Common response fields
	Response GetShopToggleInfoResponseData `json:"response"` // <p>response body<br /></p>
}
type GetShopToggleInfoResponseData struct {
	DataTimestamp int64 `json:"data_timestamp"` // [Required] <p>Timestamp of data in response<br /></p>
	AutoTopUp bool `json:"auto_top_up"` // [Required] <p>auto_top_up toggle on/off<br /></p>
	CampaignSurge bool `json:"campaign_surge"` // [Required] <p>campaign_surge toggle on/off<br /></p>
}
type GetTotalBalanceResponse struct {
	BaseResponse // Common response fields
	Response GetTotalBalanceResponseData `json:"response"` // <p>response body<br /></p>
}
type GetTotalBalanceResponseData struct {
	DataTimestamp int64 `json:"data_timestamp"` // [Required] <p>This is param to indicate the time of the snapshot of total balance<br /></p>
	TotalBalance float64 `json:"total_balance"` // [Required] <p>This is seller's ads credit balance, including paid credits and free credits.<br /></p>
}
type ListGmsUserDeletedItemRequest struct {
	Limit *int64 `json:"limit,omitempty"` // [Optional] <p>Specifies the maximum number of records to show. Default is 50. Maximum is 100.<br /></p>
	Offset *int64 `json:"offset,omitempty"` // [Optional] <p>Specifies the starting point, or the number of records to skip. Default is 0.</p>
}
type ListGmsUserDeletedItemResponse struct {
	BaseResponse // Common response fields
	Response ListGmsUserDeletedItemResponseData `json:"response"` // 
}
type ListGmsUserDeletedItemResponseData struct {
	CampaignId int64 `json:"campaign_id"` // [Required] <p>GMS Campaign ID</p>
	ItemIdList []int64 `json:"item_id_list"` // [Required] <p>List of Item IDs</p>
	Total int64 `json:"total"` // [Required] <p>Total number of Item IDs</p>
	HasNextPage bool `json:"has_next_page"` // [Required] <p>Indicate that there are more item IDs.</p>
}
type LowerBound struct {
	Value float64 `json:"value"` // [Required] <p>The ROI target value.</p>
	Percentile int64 `json:"percentile"` // [Required] <p>Competitiveness over similar ads.</p>
}
type ManualBiddingInfo struct {
	EnhancedCpc bool `json:"enhanced_cpc"` // [Required] <p>Enhanced CPC functionality&nbsp;</p>
	SelectedKeywords []ManualBiddingInfoSelectedKeywords `json:"selected_keywords"` // [Required] <p>selected keywords</p>
	DiscoveryAdsLocations []RequestDiscoveryAdsLocations `json:"discovery_ads_locations"` // [Required] <p>the location settings&nbsp;</p>
}
type ManualBiddingInfoSelectedKeywords struct {
	Keyword string `json:"keyword"` // [Required] <p>bid keywords for each campaign with search placement</p>
	Status string `json:"status"` // [Required] <p>deleted, normal, reserved, blacklist&nbsp;<br /></p>
	MatchType string `json:"match_type"` // [Required] <p>exact, broad<br /></p>
	BidPricePerClick float64 `json:"bid_price_per_click"` // [Required] <p>the bid price&nbsp;</p>
}
type Metrics struct {
	Date string `json:"date"` // [Required] <p>the given date for the performance&nbsp;</p>
	Impression int64 `json:"impression"` // [Required] <p>The number of times shoppers see your ad.</p>
	Clicks int64 `json:"clicks"` // [Required] <p>The number of times shoppers click on your ad. (Note: Shopee filters out repeated clicks from the same shopper that occur within a short time frame.)<br /></p>
	Ctr float64 `json:"ctr"` // [Required] <p>The click-through rate (CTR) measures how often shoppers end up clicking on your ad after seeing it. It is the number of clicks on your ad divided by the number of times your ad is seen. CTR = clicks ÷ impressions × 100%.</p>
	Expense float64 `json:"expense"` // [Required] <p>The amount spent on your ad.<br /></p>
	BroadGmv float64 `json:"broad_gmv"` // [Required] <p>The amount of sales revenue generated from shoppers purchasing products within 7 days of them clicking on your ad.<br /></p>
	BroadOrder int64 `json:"broad_order"` // [Required] <p>The number of times shoppers purchased any product from your shop within 7 days of them clicking on your ad.<br /></p>
	BroadOrderAmount int64 `json:"broad_order_amount"` // [Required] <p>The total quantity of products purchased by shoppers within 7 days of them clicking on your ad.<br /></p>
	BroadRoi float64 `json:"broad_roi"` // [Required] <p>Return on ad spend (ROAS) measures how much revenue is generated by your ad relative to the cost of the ad. It is the amount of sales revenue attributed to your ad divided by the amount spent on the ad. ROAS = GMV ÷ expense. (Note: We recommend monitoring ROAS trends on a weekly basis.)<br /></p>
	BroadCir float64 `json:"broad_cir"` // [Required] <p>The advertising cost of sales (ACOS) measures how much your ad costs relative to the revenue the ad generates. It is the amount spent on your ad divided by the amount of sales revenue attributed to the ad. ACOS = expense ÷ GMV × 100%.<br /></p>
	Cr float64 `json:"cr"` // [Required] <p>The conversion rate measures how often shoppers end up purchasing something from your shop after clicking on your ad. It is the number of conversions attributed to your ad divided by the number of clicks on the ad. Conversion rate = conversions ÷ clicks × 100%.<br /></p>
	Cpc float64 `json:"cpc"` // [Required] <p>The cost per conversion is how much each conversion costs, on average. It is the amount spent on your ad divided by the number of conversions attributed to the ad. Cost per conversion = expense ÷ conversions.<br /></p>
	DirectOrder int64 `json:"direct_order"` // [Required] <p>The number of times shoppers purchased the advertised product within 7 days of them clicking on the ad.<br /></p>
	DirectOrderAmount int64 `json:"direct_order_amount"` // [Required] <p>The total quantity of the advertised product purchased by shoppers within 7 days of them clicking on the ad.<br /></p>
	DirectGmv float64 `json:"direct_gmv"` // [Required] <p>The amount of sales revenue generated from shoppers purchasing the advertised product within 7 days of them clicking on the ad.<br /></p>
	DirectRoi float64 `json:"direct_roi"` // [Required] <p>The direct return on ad spend, or direct ROAS, measures how much revenue is generated from sales of the advertised product, relative to the cost of the ad. It is the amount of sales revenue for the advertised product attributed to the ad, divided by the amount spent on the ad. Direct ROAS = direct GMV ÷ expense.<br /></p>
	DirectCir float64 `json:"direct_cir"` // [Required] <p>The direct advertising cost of sales, or direct ACOS, measures how much your ad costs relative to the revenue generated from sales of the advertised product. It is the amount spent on the ad divided by the amount of sales revenue for the advertised product that is attributed to the ad. Direct ACOS = expense ÷ direct GMV × 100%.<br /></p>
	DirectCr float64 `json:"direct_cr"` // [Required] <p>The direct conversion rate measures how often shoppers end up purchasing the advertised product after clicking on the ad. Direct conversion rate is the number of direct conversions divided by the number of clicks. Direct conversion rate = direct conversions ÷ clicks × 100%.<br /></p>
	Cpdc float64 `json:"cpdc"` // [Required] <p>The cost per direct conversion is how much each direct conversion costs, on average. It is the amount spent on your ad divided by the number of direct conversions attributed to the ad. Cost per direct conversion = expense ÷ direct conversions.<br /></p>
}
type Report struct {
	BroadCir float64 `json:"broad_cir"` // [Required] <p>The direct advertising cost of sales, or direct ACOS, measures how much your ad costs relative to the revenue generated from sales of the advertised product. It is the amount spent on the ad divided by the amount of sales revenue for the advertised product that is attributed to the ad. Direct ACOS = expense ÷ direct GMV × 100%.<br /></p>
	BroadGmv float64 `json:"broad_gmv"` // [Required] <p>The amount of sales revenue generated from shoppers purchasing products within 7 days of them clicking on your ad.<br /></p>
	BroadOrder int64 `json:"broad_order"` // [Required] <p>The number of times shoppers purchased any product from your shop within 7 days of them clicking on your ad.</p>
	BroadOrderAmount int64 `json:"broad_order_amount"` // [Required] <p>The total quantity of products purchased by shoppers within 7 days of them clicking on your ad.</p>
	BroadRoi float64 `json:"broad_roi"` // [Required] <p>Return on ad spend (ROAS) measures how much revenue is generated by your ad relative to the cost of the ad. It is the amount of sales revenue attributed to your ad divided by the amount spent on the ad. ROAS = GMV ÷ expense. (Note: We recommend monitoring ROAS trends on a weekly basis.)<br /></p>
	Clicks int64 `json:"clicks"` // [Required] <p>The number of times shoppers click on your ad. (Note: Shopee filters out repeated clicks from the same shopper that occur within a short time frame.)<br /></p>
	Expense float64 `json:"expense"` // [Required] <p>The amount spent on your ad.</p>
	Cpc float64 `json:"cpc"` // [Required] <p>The cost per conversion is how much each conversion costs, on average. It is the amount spent on your ad divided by the number of conversions attributed to the ad. Cost per conversion = expense ÷ conversions.<br /></p>
	Cpdc float64 `json:"cpdc"` // [Required] <p>The cost per direct conversion is how much each direct conversion costs, on average. It is the amount spent on your ad divided by the number of direct conversions attributed to the ad. Cost per direct conversion = expense ÷ direct conversions.<br /></p>
	Cr float64 `json:"cr"` // [Required] <p>The conversion rate measures how often shoppers end up purchasing something from your shop after clicking on your ad. It is the number of conversions attributed to your ad divided by the number of clicks on the ad. Conversion rate = conversions ÷ clicks × 100%.<br /></p>
	DirectCr float64 `json:"direct_cr"` // [Required] <p>The direct conversion rate measures how often shoppers end up purchasing the advertised product after clicking on the ad. Direct conversion rate is the number of direct conversions divided by the number of clicks. Direct conversion rate = direct conversions ÷ clicks × 100%.<br /></p>
	DirectCir float64 `json:"direct_cir"` // [Required] <p>The direct advertising cost of sales, or direct ACOS, measures how much your ad costs relative to the revenue generated from sales of the advertised product. It is the amount spent on the ad divided by the amount of sales revenue for the advertised product that is attributed to the ad. Direct ACOS = expense ÷ direct GMV × 100%.<br /></p>
	DirectOrder int64 `json:"direct_order"` // [Required] <p>The number of times shoppers purchased the advertised product within 7 days of them clicking on the ad.<br /></p>
	DirectOrderAmount int64 `json:"direct_order_amount"` // [Required] <p>The total quantity of the advertised product purchased by shoppers within 7 days of them clicking on the ad.<br /></p>
	DirectRoi float64 `json:"direct_roi"` // [Required] <p>The direct return on ad spend, or direct ROAS, measures how much revenue is generated from sales of the advertised product, relative to the cost of the ad. It is the amount of sales revenue for the advertised product attributed to the ad, divided by the amount spent on the ad. Direct ROAS = direct GMV ÷ expense.<br /></p>
	Impression float64 `json:"impression"` // [Required] <p>The number of times shoppers see your ad.<br /></p>
}
type RequestDiscoveryAdsLocations struct {
	Location string `json:"location"` // [Required] <p>daily_discover, you_may_also_like<br /></p>
	Status string `json:"status"` // [Required] <p>toggle on or toggle off</p>
	BidPrice float64 `json:"bid_price"` // [Required] <p>bid price&nbsp;</p>
}
type RequestSelectedKeywords struct {
	EditAction string `json:"edit_action"` // [Required] <p>The update behaviours such as "add", "delete", "restore", "change_bid_price", "change_match_type"<br /></p>
	Keyword string `json:"keyword"` // [Required] <p>bid keyword for each campaign</p>
	MatchType *string `json:"match_type,omitempty"` // [Optional] <p>exact, broad; required if changing match type<br /></p>
	BidPricePerClick *float64 `json:"bid_price_per_click,omitempty"` // [Optional] <p>the bid price of keyword; required if changing bid price</p>
}
type ResponseDataCampaign struct {
	CampaignId int64 `json:"campaign_id"` // [Required] <p>The unique identifier for a campaign<br /></p>
	AdType string `json:"ad_type"` // [Required] <p>auto, manual<br /></p>
	CampaignPlacement string `json:"campaign_placement"` // [Required] <p>search, discovery, all<br /></p>
	AdName string `json:"ad_name"` // [Required] <p>the name of each campaign</p>
	MetricsList []CampaignMetrics `json:"metrics_list"` // [Required] <p>performance metric list</p>
}
type Result struct {
	ItemId int64 `json:"item_id"` // [Required] <p>Item ID. Results are sorted by this.<br /></p>
	Report *ResultReport `json:"report"` // [Required] 
}
type ResultReport struct {
	BroadCir float64 `json:"broad_cir"` // [Required] <p>The direct advertising cost of sales, or direct ACOS, measures how much your ad costs relative to the revenue generated from sales of the advertised product. It is the amount spent on the ad divided by the amount of sales revenue for the advertised product that is attributed to the ad. Direct ACOS = expense ÷ direct GMV × 100%.<br /></p>
	BroadGmv float64 `json:"broad_gmv"` // [Required] <p>The amount of sales revenue generated from shoppers purchasing products within 7 days of them clicking on your ad.<br /></p>
	BroadOrder int64 `json:"broad_order"` // [Required] <p>The number of times shoppers purchased any product from your shop within 7 days of them clicking on your ad.</p>
	BroadOrderAmount int64 `json:"broad_order_amount"` // [Required] <p>The total quantity of products purchased by shoppers within 7 days of them clicking on your ad.</p>
	BroadRoi float64 `json:"broad_roi"` // [Required] <p>Return on ad spend (ROAS) measures how much revenue is generated by your ad relative to the cost of the ad. It is the amount of sales revenue attributed to your ad divided by the amount spent on the ad. ROAS = GMV ÷ expense. (Note: We recommend monitoring ROAS trends on a weekly basis.)<br /></p>
	Clicks int64 `json:"clicks"` // [Required] <p>The number of times shoppers click on your ad. (Note: Shopee filters out repeated clicks from the same shopper that occur within a short time frame.)<br /></p>
	Expense float64 `json:"expense"` // [Required] <p>The amount spent on your ad.</p>
	Cpc float64 `json:"cpc"` // [Required] <p>The cost per conversion is how much each conversion costs, on average. It is the amount spent on your ad divided by the number of conversions attributed to the ad. Cost per conversion = expense ÷ conversions.<br /></p>
	Cpdc float64 `json:"cpdc"` // [Required] <p>The cost per direct conversion is how much each direct conversion costs, on average. It is the amount spent on your ad divided by the number of direct conversions attributed to the ad. Cost per direct conversion = expense ÷ direct conversions.<br /></p>
	Cr float64 `json:"cr"` // [Required] <p>The conversion rate measures how often shoppers end up purchasing something from your shop after clicking on your ad. It is the number of conversions attributed to your ad divided by the number of clicks on the ad. Conversion rate = conversions ÷ clicks × 100%.<br /></p>
	DirectCr float64 `json:"direct_cr"` // [Required] <p>The direct conversion rate measures how often shoppers end up purchasing the advertised product after clicking on the ad. Direct conversion rate is the number of direct conversions divided by the number of clicks. Direct conversion rate = direct conversions ÷ clicks × 100%.<br /></p>
	DirectCir float64 `json:"direct_cir"` // [Required] <p>The direct advertising cost of sales, or direct ACOS, measures how much your ad costs relative to the revenue generated from sales of the advertised product. It is the amount spent on the ad divided by the amount of sales revenue for the advertised product that is attributed to the ad. Direct ACOS = expense ÷ direct GMV × 100%.<br /></p>
	DirectOrder int64 `json:"direct_order"` // [Required] <p>The number of times shoppers purchased the advertised product within 7 days of them clicking on the ad.<br /></p>
	DirectOrderAmount int64 `json:"direct_order_amount"` // [Required] <p>The total quantity of the advertised product purchased by shoppers within 7 days of them clicking on the ad.<br /></p>
	DirectRoi float64 `json:"direct_roi"` // [Required] <p>The direct return on ad spend, or direct ROAS, measures how much revenue is generated from sales of the advertised product, relative to the cost of the ad. It is the amount of sales revenue for the advertised product attributed to the ad, divided by the amount spent on the ad. Direct ROAS = direct GMV ÷ expense.<br /></p>
	Impression int64 `json:"impression"` // [Required] <p>The number of times shoppers see your ad.<br /></p>
}
type SelectedKeywords struct {
	Keyword string `json:"keyword"` // [Required] <p>bid keyword for each campaign</p>
	MatchType string `json:"match_type"` // [Required] <p>exact, broad<br /></p>
	BidPricePerClick float64 `json:"bid_price_per_click"` // [Required] <p>the bid price of keyword</p>
}
type SuggestedKeywords struct {
	Keyword string `json:"keyword"` // [Required] <p>Keyword value</p><p>(Only return the highly recommended keywords, will be sightly different from Seller Center)</p>
	QualityScore int64 `json:"quality_score"` // [Required] <p>This is a measure of how attractive your ad is and its relevance to the keyword. The higher the quality score, the higher your ad rank. Ad rank is based on this score and your bid price.<br /></p>
	SearchVolume int64 `json:"search_volume"` // [Required] <p>The number of times the keyword has been searched on Shopee in the last 30 days. The larger the search volume, the more impressions your ad will receive.<br /></p>
	SuggestedBid float64 `json:"suggested_bid"` // [Required] <p>This is bid price suggested by Shopee algorithm for the keyword in local currency.<br /></p>
}
