package __PACKAGE_NAME__

// Stubs for types generated by the renderer in separate files.
// This file is NOT loaded by loadTemplate — it only exists for LSP support
// in template files.

type BaseResponse struct{}

type LeveledLogger struct{}

func (l *LeveledLogger) Debugf(format string, v ...interface{}) {}
func (l *LeveledLogger) Infof(format string, v ...interface{}) {}
func (l *LeveledLogger) Warnf(format string, v ...interface{}) {}
func (l *LeveledLogger) Errorf(format string, v ...interface{}) {}

type LeveledLoggerInterface interface {
	Debugf(format string, v ...interface{})
	Infof(format string, v ...interface{})
	Warnf(format string, v ...interface{})
	Errorf(format string, v ...interface{})
}

type Option[T any] func(any)

type DefaultOption = Option[any]
